### ISSUE TITLE
Small sample corrections

### ISSUE THREAD

**Issue by s3alfisc** [droodman/WildBootTests.jl#10]
Hi, a super low priority feature request: 

In `fwildclusterboot`, I offer users the following options to tune their small sample corrections via the `boot_ssc()` function.

1. Turn (N - 1) / (N - k) on and off
2. decide if k includes parameters that are 'not counted' for k due to fixed effects 
3. Turn G / (G-1) on and off
4. for multi-way clustering, choose G_i for all i or G_i <- min(G_i) for all i

In `WildBootTests.jl`, it is currently only possible to switch 1 and 3 jointly on and off via the `small` function arguments, and 3 can be controlled via `fedfadj`. For consistency within fwildclusterboot, it would be cool if I could offer the same small sample adjustments, i.e. if small would e.g. be changed into `small` and `small_cluster`.

**Comment by droodman** [comment]
OK, I added `clustermin` and `clusteradj` options, which correspond to the `cluster.df` and `cluster.adj` options of `fwildclusterboot`. The effect of the `small` option alone has not changed. See what you think.

A couple of other changes:

- The `fedfadj` option is no longer Boolean. Rather, it is the number of fixed-effect parameters that should be counted. So where it was false before, it should be 0, and where it was true before, it should typically be total number of fixed effects. Set it to -1 or leave it out to use the value provided in the separate `nfe` option or, if that is not provided, the number of FEs as computed by `wildboottests()`. (But it should be a little faster provide the `nfe` option, if the correct value can be extracted from the results of FE estimators in R.)
- I did change the enumerated datatypes to symbols. So one should now specify, for example, `auxwttype = :webb` or `auxwttype = "webb"`. One small change as a result is that for the `madjtype` and `diststat` options the empty values are now `:none` (or `"none"`) instead of `nomadj` and `nodist`.
